baseURL = 'https://tiagovportela.github.io/'
languageCode = 'en-us'
title = 'Tiago Portela'
theme = 'hugo-coder'

[params]
    author = "Tiago Portela"
    description = "A minimalist blog"
    keywords = "blog,developer,personal"
    info = "Full Stack Developer"
    avatarurl = "images/avatar.png" # Place an image in static/images/
    customCSS = ["css/custom.css"]

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.main]]
  name = "Blog"
  weight = 1
  url = "posts/"
