baseURL = 'https://tiagovportela.github.io/'
languageCode = 'en-us'
title = 'Tiago Portela'
theme = 'hugo-coder'

[params]
    author = "Tiago Portela"
    description = "A minimalist blog"
    keywords = "blog,developer,personal"
    info = "Full Stack Developer"
    avatarurl = "images/avatar.png" # Place an image in static/images/
    customCSS = ["css/custom.css"]
    math = true

[[params.social]]
  name = "Github"
  icon = "fa fa-2x fa-github"
  weight = 1
  url = "https://github.com/tiagovportela/"

[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-2x fa-linkedin"
  weight = 2
  url = "https://www.linkedin.com/in/tiagovportela/"

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.main]]
  name = "Blog"
  weight = 1
  url = "posts/"

[markup]
[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
